[general]
feedback_form_url = "https://docs.google.com/forms/d/e/1FAIpQLSdE--m0Q4A5LYe0sClEK21Iz268KfGaaZNGEja1QOQKN_mpeA/viewform?usp=sf_link"
contribution_url = "devpatrici0"
ga_tracking_id = "G-V6EBPS8JTG"
