name: Financial Dashboard

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting and Testing Streamlit app
        uses: streamlit/streamlit-app-action@v0.0.3
        with:
          skip-smoke: 'true'
          app-path: 'src/app.py'
          ruff: 'true'
